using System;

namespace RetroDRY
{
    //large class broken into various files! This file is just the shared items and constructor

    /// <summary>
    /// Subclassable default behavior for loading and saving datons
    /// </summary>
    public partial class RetroSql
    {
        public const string CUSTOMCOLNAME = "CustomValues";

        protected SqlFlavorizer SqlFlavor;

        /// <summary>
        /// incremented when used to generate unique alias names
        /// </summary>
        protected int MaxtDynamicAliasUsed = 0;

        public void Initialize(SqlFlavorizer.VendorKind sqlVendor)
        {
            SqlFlavor = new SqlFlavorizer(sqlVendor);
        }

        /// <summary>
        /// Determine if the database assigns primary key values for the given table (using class names, not the SQL table name)
        /// </summary>
        protected virtual bool DatabaseAssignsKeysForTable(string tableName) => true;

        /// <summary>
        /// When overridden, customizes the SQL generated by the framwwork.
        /// </summary>
        protected virtual string CustomizeSqlStatement(string sql) => sql;
    }
}
