using System;

namespace RetroDRY
{
    //large class broken into various files! This file is just the shared items and constructor

    /// <summary>
    /// Subclassable default behavior for loading and saving datons
    /// </summary>
    public partial class RetroSql
    {
        const string CUSTOMCOLNAME = "CustomValues";

        /// <summary>
        /// Defines database platform behaviors
        /// </summary>
        protected SqlFlavorizer? SqlFlavor;

        /// <summary>
        /// incremented when used to generate unique alias names
        /// </summary>
        protected int MaxtDynamicAliasUsed = 0;

        /// <summary>
        /// Initialize this instance
        /// </summary>
        /// <param name="sqlVendor"></param>
        public void Initialize(SqlFlavorizer.VendorKind sqlVendor)
        {
            SqlFlavor = new SqlFlavorizer(sqlVendor);
        }

        /// <summary>
        /// When overridden, customizes the SQL generated by the framwwork.
        /// </summary>
        protected virtual string CustomizeSqlStatement(string sql) => sql;
    }
}
